import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeScript } from "@/lib/theme/theme-script";
import { MessageProvider } from '@/contexts/MessageContext';
import { RecommendedGigsProvider } from '@/contexts/RecommendedGigsContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Supergigs",
  description: "Generated by Supergigs",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MessageProvider>
          <RecommendedGigsProvider>
            {children}
          </RecommendedGigsProvider>
        </MessageProvider>
      </body>
    </html>
  );
}